#!/usr/bin/env python
#Name: set-screen-blank.py
#Depends: python, Gtk, xset
#Author: Dave (david@daveserver.info)
#Purpose: Configure mouse on per user basis for a session. This is the gui frontend

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk, GLib
import os
import re
import gettext
gettext.install("set-screen-blank.py", "/usr/share/locale")
class Error:
    def __init__(self, parent, error):
        dlg = Gtk.MessageDialog(parent, 0, Gtk.MessageType.ERROR, Gtk.ButtonsType.OK, "Error")
        dlg.format_secondary_text(error)
        dlg.run()
        dlg.destroy()
       
class Success:
    def __init__(self, parent, success):
         dlg = Gtk.MessageDialog(parent, 0, Gtk.MessageType.INFO, Gtk.ButtonsType.OK, "Success")
         dlg.format_secondary_text(success)
         dlg.run()
         dlg.destroy()

class Var: 
    def read(self):        
        var = Var
        var.USER_HOME = os.environ['HOME']
        var.CONF_USER_DIR = var.USER_HOME+"/.desktop-session/"
        var.CONF_USER_FILE = var.CONF_USER_DIR+"desktop-session.conf"
        var.CONF_SYSTEM_FILE = "/etc/desktop-session/desktop-session.conf"
        
        if not os.path.exists(var.CONF_USER_DIR):
            os.system("mkdir %s" % (var.CONF_USER_DIR))
            os.system("cp %s %s" % ((var.CONF_SYSTEM_FILE),(var.CONF_USER_DIR)))
        else:
            if not os.path.isfile(var.CONF_USER_FILE):
                os.system("cp %s %s" % ((var.CONF_SYSTEM_FILE),(var.CONF_USER_DIR)))
            
        for line in open(var.CONF_USER_FILE, "r").xreadlines():
            if "#" not in line:
                if re.search(r'^SCREEN_BLANK_TIME=', line):
                    pieces = line.split('=')
                    OBJECT=(pieces[1])
                    OBJECT = re.sub(r'\n', '', OBJECT)
                    OBJECT = re.sub(r'"', '', OBJECT)
                    OBJECT = (int(OBJECT)/60)
                    var.blank_time = OBJECT
        
    def write(self, item):
        WRITE_FILE = Var.CONF_USER_FILE+".tmp"
        READ_FILE = Var.CONF_USER_FILE
        
        text = file((WRITE_FILE), "w");text.write("");text.close()
        text = file((WRITE_FILE), "a")
        for line in open(READ_FILE, "r").xreadlines():
            if "#" not in line:
                if re.search(r'^SCREEN_BLANK_TIME=', line):
                    text.write ("SCREEN_BLANK_TIME="+str(item)+"\n") 
                else:
                    text.write (line) 
            else:
                text.write (line) 
        text.close()        
        os.system("mv %s %s" % ((WRITE_FILE), (READ_FILE)))

class mainWindow(Gtk.Window):

    def apply(self,widget,option):
        if option == 0: #apply button
            blank_time_value = int(self.blank_time.get_value())
            blank_time_value = (blank_time_value * 60)
            Var().write(blank_time_value)
            try:
                os.system("xset dpms "+str(blank_time_value)+" "+str(blank_time_value)+" "+str(blank_time_value)+" s "+str(blank_time_value)+" "+str(blank_time_value)+" ")
            except:
                Error(self, _("Could not run set-screen-blank -set"))
            else:
                Success(self, _("Screen blank time has been set to: \n"+str(blank_time_value/60)+" minutes or "+str(blank_time_value)+" seconds" ))

    def scale_set_default_values(self, scale, option):
        scale.set_digits(option)
        scale.set_draw_value(True)

    def __init__(self):
        Gtk.Window.__init__(self)
        self.set_size_request(300,0)
        self.set_border_width(10)
        
        mainframe = Gtk.Frame(label="Screen Blank Time")
        self.add(mainframe)
        self.grid = Gtk.Grid()
        mainframe.add(self.grid)
        
        infobox = Gtk.HBox()
        infobox.set_border_width(10)
        self.grid.attach(infobox, 1, 1, 1, 1)
        
        label = Gtk.Label()
        label.set_text(_("  Turn on/off screen blank timeout  "))
        infobox.pack_start(label, True,True,0)
        label.show()
        
        sliderbox = Gtk.VBox()
        sliderbox.set_border_width(10)
        self.grid.attach(sliderbox, 1, 2, 2, 1)
        
        label = Gtk.Label()
        label.set_text(_("  Time before screen blanks (Minutes)  "))
        sliderbox.pack_start(label, True,True,0)
        label.show()
        
        adj1 = Gtk.Adjustment(float(Var.blank_time), 0, 120, 1, 5, 1)
        self.blank_time = Gtk.HScale()
        self.blank_time.set_adjustment(adj1)
        #self.blank_time.set_size_request(200, 45)
        self.scale_set_default_values(self.blank_time, 0)
        sliderbox.pack_start(self.blank_time, True, True, 0)
        self.blank_time.show()
        
        self.switch = Gtk.Switch()
        self.switch.set_active(True)
        self.grid.attach(self.switch, 2, 1, 1, 1)
        
        
        #BUTTON BOX
        
        buttonbox = Gtk.HButtonBox()
        buttonbox.set_border_width(10)
        self.grid.attach(buttonbox, 2, 4, 1,1)
        buttonbox.show()
        
        aply = Gtk.Button(stock=Gtk.STOCK_APPLY)
        aply.connect("clicked", self.apply, 0)
        buttonbox.pack_start(aply, True, True, 0)
        aply.show()
        
        close = Gtk.Button(stock=Gtk.STOCK_CLOSE)
        close.connect("clicked", lambda w: Gtk.main_quit())
        buttonbox.add(close)
        close.show()

Var().read()
win = mainWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
